[package]
name = "mdcs"
version = "0.1.0"
authors = ["Alexandru Barbur <alex@ctrlc.name>"]
edition = "2018"

[dependencies]
# avro-rs = "0.6"
avro-rs = { git = "https://github.com/CtrlC-Root/avro-rs", branch = "dev" }
