[package]
name = "mdcs"
version = "0.1.0"
authors = ["Alexandru Barbur <root.ctrlc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
